variable "subscription_id" {}
variable "location" {}
variable "resource_group_name" {}
variable "storage_account_name" {}
variable "container_name" {}
variable "vnet_name" {}
variable "address_space" {}
variable "subnet_name" {}
variable "subnet_prefix" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "account_kind" {}
variable "container_access_type" {}