variable "subscription_id" {}
variable "resource_group_name" {}
variable "location" {}
variable "vm_name" {}
variable "admin_username" {}
variable "admin_password" {}
variable "disk_name" {}
variable "disk_size_gb" {}
variable "disk_sku" {}
variable "caching" {}
variable "lun" {}